language: node_js
node_js:
 - 18
cache:
 directories:
   - node_modules
script:
 - npm run eslint
 - npm run stylelint
# deploy:
#  provider: pages
#  skip_cleanup: true
#  github_token: $GITHUB_TOKEN
#  local_dir: build
#  on:
#    branch: master